### ISSUE TITLE
[samba-mounter] enable password auth

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.8#37] opened 2016-11-24 20:54 UTC
Password auth requested to be made useable:
https://forums.mauilinux.org/showthread.php?tid=24126&page=2

**Comment by star-buck** [comment] 2016-11-30 11:26
@aleixpol : can you add password auth for samba-mounter and/or ask afiestas about his thoughts for this?

**Comment by aleixpol** [comment] 2016-12-01 01:30
Fixed as of https://cgit.kde.org/scratch/afiestas/samba-mounter.git/commit/?id=9869c1fc6948c59a0bc839ff78ed9625fe9f225b

**Comment by star-buck** [comment] 2016-12-01 08:08
Thanks a lot, will update packages and close after testing.

**Comment by star-buck** [comment] 2017-01-12 21:29
works!

**Comment by star-buck** [comment] 2017-01-13 10:15
just reopen to check if this has anything todo with the recent changes we made:
https://forums.mauilinux.org/showthread.php?tid=24229&pid=41323#pid41323

**Comment by aleixpol** [comment] 2017-01-13 11:43
I doubt the commit here is the culprit because it was broken beforehand. We need to be able to reproduce though, to get a fix. Or at least to know how his case is different...

**Closed** 2017-01-21 23:33 UTC
Labels: ready for QA
